package com.yetland.data.database.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yetland.data.database.BaseCacheEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BASE_CACHE_ENTITY".
*/
public class BaseCacheEntityDao extends AbstractDao<BaseCacheEntity, Long> {

    public static final String TABLENAME = "BASE_CACHE_ENTITY";

    /**
     * Properties of entity BaseCacheEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, String.class, "objectId", false, "OBJECT_ID");
        public final static Property Value = new Property(2, String.class, "value", false, "VALUE");
        public final static Property Owner = new Property(3, String.class, "owner", false, "OWNER");
    }


    public BaseCacheEntityDao(DaoConfig config) {
        super(config);
    }
    
    public BaseCacheEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BASE_CACHE_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"OBJECT_ID\" TEXT," + // 1: objectId
                "\"VALUE\" TEXT," + // 2: value
                "\"OWNER\" TEXT);"); // 3: owner
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BASE_CACHE_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BaseCacheEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(3, value);
        }
 
        String owner = entity.getOwner();
        if (owner != null) {
            stmt.bindString(4, owner);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BaseCacheEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(3, value);
        }
 
        String owner = entity.getOwner();
        if (owner != null) {
            stmt.bindString(4, owner);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public BaseCacheEntity readEntity(Cursor cursor, int offset) {
        BaseCacheEntity entity = new BaseCacheEntity( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // objectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // value
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // owner
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BaseCacheEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setObjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setValue(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOwner(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BaseCacheEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BaseCacheEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BaseCacheEntity entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
