package com.yetland.data.database.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yetland.data.database.BaseCacheEntity;

import com.yetland.data.database.greenDao.BaseCacheEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseCacheEntityDaoConfig;

    private final BaseCacheEntityDao baseCacheEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baseCacheEntityDaoConfig = daoConfigMap.get(BaseCacheEntityDao.class).clone();
        baseCacheEntityDaoConfig.initIdentityScope(type);

        baseCacheEntityDao = new BaseCacheEntityDao(baseCacheEntityDaoConfig, this);

        registerDao(BaseCacheEntity.class, baseCacheEntityDao);
    }
    
    public void clear() {
        baseCacheEntityDaoConfig.clearIdentityScope();
    }

    public BaseCacheEntityDao getBaseCacheEntityDao() {
        return baseCacheEntityDao;
    }

}
